displayName=Xp To Level Notification
author=Robin Davidsson
description=A plugin that sends a notification when you're less than the specified amount of xp away from a level
tags=experience,exp,xp,left,notification,
version=1.1
plugins=com.vanillj.xptolevelnotification.XpToLevelNotificationPlugin
build=standard
